template:
  direction: Horizontal
  parts:
    - direction: Vertical # part 2
      body: true
    - direction: Vertical # part 3
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:compact-bar"
